### ISSUE TITLE
Date filter popup shows preselected dates, but values are null

### ISSUE THREAD

**Issue by ghost** [tepi/FilteringTable#102]
Vaadin 7.4.3, FilteringTable 0.9.13.v7 (Chrome, Firefox)

When the date filter popup comes up, today's date appears selected for both from- and to-date calendars. Selecting a from-date, and leaving the to-date as is results in a comparison error, though debugging shows the to-date is actually null (trace below). Everything works fine if both the from- and to-dates are picked. I would like for the dates to not show in "selected" state initially, forcing the user to select values. Any advice or experience from others regarding this will be greatly appreciated. 

Thanks,
Sue

![image](https://cloud.githubusercontent.com/assets/3299857/11849925/02d1c8e2-a3f0-11e5-8689-1e33ae28a82a.png)

`com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in org.tepi.filtertable.FilterFieldGenerator$2 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003)
    at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1159)
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:570)
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
    at com.vaadin.ui.AbstractField.setValue(AbstractField.java:453)
    at org.tepi.filtertable.datefilter.DateFilterPopup.setValue(DateFilterPopup.java:75)
    at org.tepi.filtertable.datefilter.DateFilterPopup.updateValue(DateFilterPopup.java:204)
    at org.tepi.filtertable.datefilter.DateFilterPopup.access$100(DateFilterPopup.java:36)
    at org.tepi.filtertable.datefilter.DateFilterPopup$1.buttonClick(DateFilterPopup.java:96)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003)
    at com.vaadin.ui.Button.fireClick(Button.java:394)
    at com.vaadin.ui.Button$1.click(Button.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:313)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:202)
    at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:153)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:232)
    at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:492)
    at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:88)
    at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:78)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
    at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:795)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:527)
    at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:104)
    at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: Could not compare the arguments: 2002-04-08, Sun Dec 13 12:13:26 CST 2015
    at com.vaadin.data.util.filter.Compare.compareValue(Compare.java:299)
    at com.vaadin.data.util.filter.Compare.passesFilter(Compare.java:258)
    at com.vaadin.data.util.AbstractInMemoryContainer.passesFilters(AbstractInMemoryContainer.java:555)
    at com.vaadin.data.util.AbstractInMemoryContainer.doFilterContainer(AbstractInMemoryContainer.java:526)
    at com.vaadin.data.util.AbstractInMemoryContainer.filterAll(AbstractInMemoryContainer.java:487)
    at com.vaadin.data.util.AbstractInMemoryContainer.addFilter(AbstractInMemoryContainer.java:583)
    at com.vaadin.data.util.AbstractBeanContainer.addContainerFilter(AbstractBeanContainer.java:385)
    at org.tepi.filtertable.FilterFieldGenerator.setFilter(FilterFieldGenerator.java:369)
    at org.tepi.filtertable.FilterFieldGenerator.updateFilterForField(FilterFieldGenerator.java:572)
    at org.tepi.filtertable.FilterFieldGenerator.access$100(FilterFieldGenerator.java:44)
    at org.tepi.filtertable.FilterFieldGenerator$2.valueChange(FilterFieldGenerator.java:535)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 57 common frames omitted`

**Comment by tepi** [comment]
Hi,

I'm unable to reproduce this issue, please see the attachment for how it works for me.
![screen shot 2016-01-20 at 11 55 05](https://cloud.githubusercontent.com/assets/1527900/12445420/cea3c050-bf6c-11e5-94d0-750d24b98300.png)
On the left side I have not yet selected anything and it just shows today's date with the box, on the right side I picked a date so it's shown in blue.

**Comment by yaffet** [comment]
Hello,

I have exact the same issue in my project. So far i have researched this is the cause of failure: 
`java.lang.IllegalArgumentException: Could not compare the arguments: 2002-04-08, Sun Dec 13 12:13:26 CST 2015`
If you choose one date from the date pop-up and the other date comes from your data container, it can lead to this exception. The date might not neccessarly be in the same format and as such the compare of the vaadin filter fails, as it states that they obvisiouly look different: date from database 1: 2002-04-08 date 2 from date pop-up: Sun Dec 13 12:13:26 CST 2015.

I hope this helps with further investigation.

**Comment by yaffet** [comment]
I've found a small workaround for this problem. I converted the Date i received from database to Calendar and converted it back to Date:
`Calendar cal = new GregorianCalendar();`
`cal.setTime(date);`
`return cal.getTime();`
This solved the problem for me though it isn't a very good solution in my opinion.

**Comment by tepi** [comment]
The fault does not seem to be in the add-on. Instead the dates in the calendar are different type/format than dates in the date filter component. Please modify your container data or provide a custom Filter implementation to handle this issue.
