### ISSUE TITLE
findNumRowsToPaint throws NullPointerException (sometimes)

### ISSUE THREAD

**Issue by fracz** [tepi/FilteringTable#46]
Sometimes (I have not figured out the reproduce path yet), the folllowing exception is being thrown when attaching `FilterTable` component:

```
java.lang.NullPointerException
    at com.vaadin.ui.CustomTable.findNumRowsToPaint(CustomTable.java:3702)
    at com.vaadin.ui.CustomTable.doPaintContent(CustomTable.java:3210)
    at com.vaadin.ui.CustomTable.paintContent(CustomTable.java:3196)
    at org.tepi.filtertable.FilterTable.paintContent(FilterTable.java:69)
    at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
    at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:81)
    at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:106)
    at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:149)
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:97)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1382)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

FilteringTable 0.9.2.v7, Vaadin 7.1.9.

Maybe someone have an idea what's going on.

**Comment by mishamo** [comment]
This is also happening for me with filteringtable 0.9.11v7. A strange case that makes this reproducible for us is that if you press "enter" to confirm a filter then this exception is thrown, if you let the filter kick in itself (with the delay-timer) then everything works just fine. The use case for us is as follows:
 - FilterTable components within a TabSheet
 - Filter a String-based column by its full value
 - Press enter to commit the filter
 - Switch to another tab (renders another table)
 - Switch back to the original tab

Throws this:
```
java.lang.NullPointerException
  at com.vaadin.ui.CustomTable.findNumRowsToPaint  (line 3766)
  at com.vaadin.ui.CustomTable.doPaintContent  (line 3274)
  at com.vaadin.ui.CustomTable.paintContent  (line 3260)
  at org.tepi.filtertable.FilterTable.paintContent  (line 74)
  at com.vaadin.server.LegacyPaint.paint  (line 65)
  at com.vaadin.server.communication.LegacyUidlWriter.write  (line 82)
  at com.vaadin.server.communication.UidlWriter.write  (line 115)
  at com.vaadin.server.communication.AtmospherePushConnection.push  (line 166)
  at com.vaadin.server.communication.AtmospherePushConnection.push  (line 144)
  at com.vaadin.ui.UI.push  (line 1512)
  at com.vaadin.server.VaadinSession.unlock  (line 1026)
  at com.vaadin.server.VaadinService.requestEnd  (line 1355)
  at com.vaadin.server.communication.PushHandler.callWithUi  (line 293)
  at com.vaadin.server.communication.PushHandler.access$200  (line 58)
  at com.vaadin.server.communication.PushHandler$1.onRequest  (line 78)
  at org.atmosphere.cpr.AsynchronousProcessor.action  (line 205)
  at org.atmosphere.cpr.AsynchronousProcessor.suspended  (line 104)
  at org.atmosphere.container.JettyWebSocketUtil.doService  (line 70)
  at org.atmosphere.container.JettyServlet30AsyncSupportWithWebSocket.service  (line 52)
  at org.atmosphere.cpr.AtmosphereFramework.doCometSupport  (line 2075)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch  (line 570)
  at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run  (line 332)
  at org.atmosphere.util.VoidExecutorService.execute  (line 101)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch  (line 327)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol  (line 424)
  at org.atmosphere.container.JettyWebSocketHandler.onMessage  (line 97)
  at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameHandler.onFrame  (line 835)
  at org.eclipse.jetty.websocket.WebSocketParserRFC6455.parseNext  (line 349)
  at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455.handle  (line 225)
  at org.eclipse.jetty.io.nio.SslConnection.handle  (line 196)
  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle  (line 668)
  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run  (line 52)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob  (line 608)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run  (line 543)
  at java.lang.Thread.run  (line 745)
```
