### ISSUE TITLE
findNumRowsToPaint throws NullPointerException 

### ISSUE THREAD

**Issue by ikus060** [tepi/FilteringTable#78]
In reference to #46 , I'm experiencing this exception too with version 0.9.11.v7. While some user can reproduce it every time, others never saw it. Users having this issue, only enter a value in a filter and refresh the table: calling table.getContainerSource().refresh();

java.lang.NullPointerException
        at com.vaadin.ui.CustomTable.findNumRowsToPaint(CustomTable.java:3766)
        at com.vaadin.ui.CustomTable.doPaintContent(CustomTable.java:3274)
        at com.vaadin.ui.CustomTable.paintContent(CustomTable.java:3260)
        at org.tepi.filtertable.FilterTable.paintContent(FilterTable.java:74)
        at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
        at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:116)
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:151)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:99)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1402)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:711)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1112)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1046)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:724)

**Comment by codelurch** [comment]
Anything new about this? This one is hitting me seriously...

**Comment by plel** [comment]
We are also affected by this bug, but were so far unable to reproduce it. Can anybody confirm that pull request #77 fixes the issue?
