### ISSUE TITLE
Date filters on JPAContainer backed FilterTable that has no result causes NPE

### ISSUE THREAD

**Issue by rgunn** [tepi/FilteringTable#82]
This behaviour happens using the default date filter prompts on a JPAContainer backed  FilteringTable.Applying a date range on filter table that returns no results causes a NPE in

JPAContainer:
    public boolean isLastId(Object itemId) {
        assert itemId != null : "itemId must not be null";
        return itemId.equals(lastItemId());
    }

This is after the table fires an item set change.

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/4567115/5574222/98a8befe-900d-11e4-80eb-fc4e137604e2.png)

Caused by: java.lang.NullPointerException
    at com.vaadin.addon.jpacontainer.JPAContainer.isLastId(JPAContainer.java:573)
    at com.vaadin.ui.CustomTable.isLastId(CustomTable.java:4644)
    at com.vaadin.ui.Table.isLastId(Table.java:4673)
    at com.vaadin.ui.Table.setCurrentPageFirstItemIndex(Table.java:1557)
    at com.vaadin.ui.Table.containerItemSetChange(Table.java:4540)
    at com.vaadin.ui.AbstractSelect.fireItemSetChange(AbstractSelect.java:1708)
    at com.vaadin.ui.AbstractSelect.containerItemSetChange(AbstractSelect.java:1679)
    at com.vaadin.ui.CustomTable.containerItemSetChange(CustomTable.java:4503)
    at com.vaadin.addon.jpacontainer.JPAContainer.fireContainerItemSetChange(JPAContainer.java:262)
    at com.vaadin.addon.jpacontainer.JPAContainer$1.filtersApplied(JPAContainer.java:179)
    at com.vaadin.addon.jpacontainer.filter.util.AdvancedFilterableSupport.fireListeners(AdvancedFilterableSupport.java:99)
    at com.vaadin.addon.jpacontainer.filter.util.AdvancedFilterableSupport.applyFilters(AdvancedFilterableSupport.java:222)
    at com.vaadin.addon.jpacontainer.filter.util.AdvancedFilterableSupport.addFilter(AdvancedFilterableSupport.java:256)
    at com.vaadin.addon.jpacontainer.JPAContainer.addContainerFilter(JPAContainer.java:1006)
    at org.tepi.filtertable.FilterFieldGenerator.setFilter(FilterFieldGenerator.java:369)
    at org.tepi.filtertable.FilterFieldGenerator.updateFilterForField(FilterFieldGenerator.java:571)
    at org.tepi.filtertable.FilterFieldGenerator.access$100(FilterFieldGenerator.java:43)
    at org.tepi.filtertable.FilterFieldGenerator$2.valueChange(FilterFieldGenerator.java:534)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by tepi** [comment]
Not relevant anymore. The CustomTable class is no longer used.
